import Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part1
import Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part2
import Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part3
import Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part4
